import { faker } from '@faker-js/faker';
import mysql from 'mysql2/promise';
// 1. Cấu hình kết nối (Lưu ý Port 3306 phải được map ra từ Docker)
const dbConfig = {
    host: 'localhost',
    user: 'root',      // User root của Database (trong docker-compose)
    password: 'root',  // Password root
    database: 'orangehrm',
    port: 3306
};

// Số lượng nhân viên muốn tạo
const NUM_EMPLOYEES = 50;

// Danh sách Job Title mẫu
const JOB_TITLES = [
    'Backend Developer', 'Frontend Developer', 'DevOps Engineer', 
    'QA Automation', 'Business Analyst', 'HR Specialist'
];

async function main() {
    let connection;
    try {
        console.log('Đang kết nối Database...');
        connection = await mysql.createConnection(dbConfig);
        console.log('Kết nối thành công!\n');

        // --- BƯỚC 1: TẠO JOB TITLES ---
        console.log('Creating Job Titles...');
        const jobIds = [];

        for (const title of JOB_TITLES) {
            // Check xem Job đã có chưa
            const [rows] = await connection.execute(
                'SELECT id FROM ohrm_job_title WHERE job_title = ?', 
                [title]
            );

            if (rows.length > 0) {
                jobIds.push(rows[0].id);
            } else {
                // Nếu chưa có thì Insert
                const [result] = await connection.execute(
                    'INSERT INTO ohrm_job_title (job_title, job_description, is_deleted) VALUES (?, ?, 1)',
                    [title, 'Generated by Nodejs Tool']
                );
                jobIds.push(result.insertId);
                console.log(`   + Inserted Job: ${title}`);
            }
        }

        // --- BƯỚC 2: TẠO NHÂN VIÊN ---
        console.log(`\nGenerating ${NUM_EMPLOYEES} employees...`);
        
        const employeeValues = [];
        
        for (let i = 0; i < NUM_EMPLOYEES; i++) {
            const firstName = faker.person.firstName();
            const lastName = faker.person.lastName();
            const employeeId = faker.string.numeric(5); // Mã NV 5 số ngẫu nhiên
            
            // Random Job ID từ list trên
            const randomJobId = jobIds[Math.floor(Math.random() * jobIds.length)];

            // Push vào mảng để Insert Bulk (Nhanh hơn insert từng dòng)
            // hs_hr_employee(emp_number, employee_id, emp_lastname, emp_firstname, job_title_code)
            employeeValues.push([null, employeeId, lastName, firstName, randomJobId]);
        }

        // Query Insert Bulk
        const sql = 'INSERT INTO hs_hr_employee (emp_number, employee_id, emp_lastname, emp_firstname, job_title_code) VALUES ?';
        
        const [res] = await connection.query(sql, [employeeValues]);
        
        console.log(`Đã insert thành công ${res.affectedRows} nhân viên!`);

    } catch (err) {
        console.error('Có lỗi xảy ra:', err.message);
    } finally {
        if (connection) await connection.end();
        console.log('Đã đóng kết nối.');
    }
}

main();